id = "7a0deb4d-1adb-499e-a2a9-92229456254a"
name = "Map 4"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 1
y = 1
w = 2
h = 2

grid = """
                                                                                                   
                                                                                         ###       
                                                                                       #   #       
                                                             #    ####                     #       
                                                  ## ##       ####    ## #### ##      #   ##       
                                                #   ###       #           ## ### ##  #   #  #      
                                                   #####      ######### #       ##   #  # ####     
                                               ####  #        #                   #  #  # ###      
                                              #  ## ##  #                          #  #### # #     
                                              #  #####  #    ##                    #   #           
                                              ########       #                     # #  ##  #      
                                               # ##  #  #   #                      # ####          
                                                ## ## #     #                      #     ###       
                                                            #                      #               
                                                            #    ########### #######               
                                                             #####                                 
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                          ## # # # #  #   #  # ### 
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                           #   #    #      #       
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                          ##                                                                       
                                                                                                   
                                                                                                   
                        #                                                                          
                                                                                                   
                                                                                                   
                     #                                                                             
                                                                                                   
                   #                                                                               
                                                                                                   
                 #                                                                                 
               #                                                                                   
              #                                                                                    
                                                                                                   
              #                                                                                    
            ##                                                                                     
"""

[exits]
left = "61d3cae3-9ce6-4b1e-963c-1ab5dcd86204"
top = "d6b0a6a1-9f33-4edc-a3d5-8b22f6f1aa77"
bottom = "e5c18430-e7ab-4a70-9fc7-898d191ef2fb"
