id = "d14f996a-d287-495d-953e-38daee136c65"
name = "Mountain Fork"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 48
y = 32
w = 2
h = 2

grid = """
                                         #               #                                         
                                          #              ##                                        
                                          #               #                                        
                                          #               #                                        
                                          #               #                                        
                                          #               #                                        
                                          #               ##                                       
                                          #                #                                       
                                          #                #                                       
                                         ##                #                                       
                                         #                 #                                       
                                         #                 #                                       
                                         #                 #                                       
                                         #                 #                                       
                                         #                 ##                                      
                                         #                  #                                      
                                         #                  #                                      
                                         #                  #                                      
                                         #                  #   #                                  
                                         #                  ##  #                                  
                                         #                   #                                     
############                             #                   #                                     
           ######                       ##                   #                                     
                ####                    #                    ##                                    
                   ##                  ##                     #                                    
                     ###               #                      #                                    
                       #################                      #                                    
                                                               #                                   
                                                               #                                   
                                                               ##                                  
                                                                #                                  
                                                                #                                  
                                                                ##                                 
                                                                 #                                 
                                                                 #                                 
############                                                     #                                 
           ###                         #                         ##                                
             ###                                                  #                                
               ####                                               #                                
                  #######                                        ##                                
                         #####                                   #                                 
                             #####                              ##                                 
                                 ###                           ##                                  
                                   ###                        ##                                   
                                     ##                       #                                    
                                      #                      ##                                    
                                      ##                     #                                     
                                       #                    ##                                     
                                       ##                   #                                      
                                        #                   #                                      
                                        #                   #                                      
                                        #                   #                                      
                                       ##                   #                                      
                                     ####                   #                                      
                                    ##  #                   #                                      
                                    #   #                   #                                      
                                    #   #                   #                                      
                                    #   #                   #                                      
                                    #   #                   #                                      
                                    #   #                   #                                      
                                    #   ##                  #                                      
                                    #    #                  #                                      
                                    #    #                  #                                      
                                    #    #                  #                                      
                                    #   ##                  #                                      
                                    ##  #                   #                                      
                                     # ##                   #                                      
                                     ###                   ##                                      
                                      ##                   #                                       
                                      #                   ##                                       
"""

[layers.background]
image = "bg/mountain-fork.png"

[exits]
left = "285b2403-e81c-4d61-9a1e-060bcb156828"
top = "720fd469-18c2-4298-bb39-b1be0a3e9d15"
bottom = "609aa6a9-2caa-421f-92a7-e7782a3926d0"
