id = "e5c18430-e7ab-4a70-9fc7-898d191ef2fb"
name = "South Road"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 1
y = 1
w = 2
h = 2

grid = """
                                                                                                   
                                                                                                   
                             #                                                                     
                            # ##                        ########################################   
                           #    #                       #                                      #   
                         ##      ##                     #                                      #   
                        #          #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #           #                    #                                      #   
                       #############                    #                                      #   
                                                        #                                      #   
                                                        #                                      #   
                                                        #                                      #   
                                                        #                                      #   
                                                        #                                      #   
                                                        #                                      #   
                                                        #                                      #   
                                                        #                                      #   
  ########################################              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              #                                      #   
  #                                      #              ########################################   
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  #                                      #                                                         
  ########################################                                                         
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
"""

[layers.background]
image = "bg/south-road.png"

[exits]
top = "7a0deb4d-1adb-499e-a2a9-92229456254a"
bottom = "720fd469-18c2-4298-bb39-b1be0a3e9d15"
