id = "720fd469-18c2-4298-bb39-b1be0a3e9d15"
name = "Map 6"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 1
y = 1
w = 2
h = 2

grid = """
                                                                                                   
                                                                                                   
                                                              ##                                   
                                                             ###  ###                       #####  
 #     ###                                                    ##  ###         ###          ####### 
###    ###                                                                    ###          ####### 
###    ##                  ###                                                 ##           ###### 
 ##                       ####                                                              ###### 
                          ####            ##                                                  ###  
                                         ####                                                      
                                          ###                                                      
                                                                                                   
                                       #                                                           
                                      ###                                                          
                                      ###                                                          
                                       ##                                                          
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
  ###                                                                                              
 ####                                                                                              
 ####                                                                                              
 ####                                                                                          ##  
 ####                                                                                         #### 
                                                                                              ###  
          ###                                                                                      
          ###                                                                                      
##        ###  #                                                                                   
 ###          ####                                                                                #
   ###        ####                                                                               # 
     ##    ##  ###                                                                             ### 
      ###  ###                                                                            ######   
#       ## ###                                                                  ####      #        
 ##      #####           ##                                                     ####     ##        
   ##      ##            ###                                                     ##     ##         
     ##     #           ####                                                          ###          
       ##   #            ###                                                        ###            
         #  #                                                                    ####              
          ####                                                                 ###                 
            ###                         ###                                   ##                   
              ##           #######      ###                             #######                    
                ##         ########     ##                            ###                          
                  #        #### ###                                 ###                            
                   ##       ###                         ###         #                              
                     ####                               ###    ######                              
                       #######                          ##   ###                                   
                         ##  ####                           ##                                     
                           ##   ###                        ##                                      
                             #    ###                     ##                                       
                              ##    ###                 ###                                        
                                ##    ###   ###        ##                                          
                                  ##    ##### ##       #                                           
                                    ##         #       #                                           
                                      #        #       #                                           
                                       ##      #       #                                           
                                         ##    #       #                                           
                                           ##  #       #                                           
                                             ###       #                                           
                                               #       #                                           
                                               #       #                                           
                                               #       #                                           
                                               #       #                                           
"""

[layers.background]
image = "bg/to-mountain.png"

[exits]
top = "e5c18430-e7ab-4a70-9fc7-898d191ef2fb"
bottom = "d14f996a-d287-495d-953e-38daee136c65"
