id = "285b2403-e81c-4d61-9a1e-060bcb156828"
name = "Mountain Hut"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 1
y = 1
w = 2
h = 2

grid = """
        #                                                           ##                             
        #    ##########################################              ##                            
        #    #                                        #               ##                           
        #    #                                        #                #                           
       ##    #                                        #                ##                          
      ##     #                                        #                 #                          
      #      #                                        #                 ##                         
     ##      #                                        #                  ##                        
     #       #                                        #                   ##                       
    ##       #                                        #                    #                       
    #        #                                        #                    #                       
    #        #                                        #                   ##                       
    #        #                                        #                  ##                        
    #        #                                        #                  #                         
   ##        #                                        #                 ##                         
   #         #                                        #                 #                          
   #         #                                        #                ##           #########      
   #         #                                        #               ##          ###       ##     
   #         #                                        #               #           #          ##    
  ##         #                                        #               ##      #####           #####
  #          #                                        #                #########                   
  #          #                                        #                                            
 ##          #                                        #                                            
 #           #                                        #                                            
##           ###########    ###########################                                            
#                                                                                                  
#                                                                                                  
                                                                                                   
                                                                                                   
                                                                                                   
                  #####                                                                            
                ########                                                                           
                #########                                                                          
               ##########                                                                          
               ##########  ##                                                                      
               ##########  ##                                                                      
                ########                                                                           
                ########                                                                          #
                  #####                                                                           #
                   ###                                                                          ###
                                                                                              ###  
                                                                                            ###    
                                                                                          ###      
                                                                                       ####        
                                                                                     ###           
                                                                                  ###              
                                                                                 ##                
                                                                                ##                 
#                                                                              ##                  
##                                                                            ##                   
 ##                                                                          ##                    
   ###                                                                       #                     
     ####                                                                    #                     
        ##                                                                  ##                     
         ###                                                                #                      
           ##                                                               #                      
            ##                                                             #                       
             ##                                                            #                       
              ###                                                         ##                       
                ###                                                       #                        
                  ####                                                    #                        
                     ##                                                  ##                        
                      ##                                                ##                         
                       ###                                              #                          
                         ##                                            ##                          
                          ###                                         ##                           
                            ####                                      #                            
                               ##                                    ##                            
                                ###                                  #                             
                                  ####                              #                              
"""

[layers.background]
image = "bg/mountain-hut.png"

[exits]
right = "d14f996a-d287-495d-953e-38daee136c65"
