id = "a1e4f9f0-55e8-4778-b0cc-0d6a6f1b0c11"
name = "Home"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 10
y = 6
w = 2
h = 2

[story]
on_load_sequence = "dreamsequence_001"

grid = """
                                                                                                   
                                                                                                   
         #####################################                                                     
         #                                   #             #################################       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             #                               #       
         #                                   #             ####################     ########       
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         ########     ########################                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                                                                         
         #                                                                                         
         #                                                                                         
         #                                                                                         
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         #                                   #                                                     
         ########     ########################                                                     
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
"""

[layers.background]
image = "bg/home-night.png"

[exits]
right = "d6b0a6a1-9f33-4edc-a3d5-8b22f6f1aa77"
