id = "609aa6a9-2caa-421f-92a7-e7782a3926d0"
name = "Road to bridge"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 1
y = 1
w = 2
h = 2

grid = """
                                                          #                                        
                                       #                  #          ##############                
                                       #                  #                       #####            
                         ####         ##                  #         ##                #######      
                  ########  #         #                   #          ###                           
               ####       ###        ##                   #            ##                          
        #######          ##          #                    #         #    ##                        
     ####             ###            #                    #         #      ###                     
                    ###              #                    #         #        ###                   
                   ##      ###      ##                    #          ##        ####                
                  ##  ######        #                     #           ###         #######          
        ###############             #                     #             ###                        
       ##    ###                    #                     #               ####                     
       #######                      #                    #                   ###                   
   ######                           ##                   #                      #####              
####  #                              #                   #                          ###            
                                     #                   #                            ###          
                                     #                   ##                             ##         
                                     ##                   #                              ###       
                                      #                   #                                ###     
                                      #                   #                                  ###   
                                      #                   ##                                   #   
                                      #                    #                                       
                                      ##                   #                                       
                                       #                   #                                       
                                       #                   #                                       
                                       #                   #                                       
                                       #                   #                                       
                                       ##                  #                                       
                                        #                  #                                       
                                        #                  #                                       
                                        ##                 #                                       
                                         #                 #                                       
                                         #                 #                                       
                                         ##                #                                       
                                          #                #                 #                     
                                          #                #                 #######               
                                           #               #                 #     #               
                                           #               ##                #     ##              
                                           #                #                #      #              
                                           #                #                #      #              
                                           ##               #                #      #              
                                            #               ##               #      #              
                                            #                #               #   ####              
                                            #                #               #####                 
                                            #                 #                                    
                                            #                 #                                    
                                            #                 #                                    
                                            #                 #                                    
                                            #                 ##                                   
                                            #                  #                                   
                ####                        #                  #                                   
               ##  #                        #                 ##                                   
                   ##                        #                #                                    
                    #                        #                #                                    
               #    #                        #                #                                    
               #   ##                       ##                #                                    
               #####                        #                 #                                    
                                           #                  #                                    
                                          ##                 ##                                    
                                          #                  #                                     
                                          #                  #                                     
                                         #                   #                                     
                                         #                   #                                     
                                         #                   #                                     
                                         #                  ##                                     
                                         #                  #                                      
                                         #                  #                                      
                                         #                  #                                      
                                         #                  #                                      
"""

[exits]
top = "d14f996a-d287-495d-953e-38daee136c65"
