id = "61d3cae3-9ce6-4b1e-963c-1ab5dcd86204"
name = "town square"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 1
y = 1
w = 2
h = 2

grid = """
                                                                                                   
                                                                                                   
                                                                                                   
        #################################################################################          
        #                           #    #                                              #          
        #                           #    #                                              #          
        #   #########################    #############################################  #          
        #   #                       #    #                                           #  #          
        #   #                       #    #                                           #  #          
        #   #                       #    #                                           #  #          
        #   #                       #    #                                           #  #          
        #   #                       #    #                                           #  #          
        #   #                       #    #                                           #  #          
        #   #                       #    #######################################     #  #          
        #   #                       #                                          #     #  #          
        #   #                       #                                          #     #  #          
        #   #                       #                                          #     #  #          
        #   #                       #                                          #     #  #          
        #   #                       ############################################     #  #          
        #   #                                                                        #  #          
        #   #                                                                        #  #          
        #   #                                                                                      
        #   #                                                                                      
        #   #                                                                                      
        #   #                                                                        #  #          
        #   #                                                                        #  #          
        #   #                                                                        #  #          
        #   #                                                                        #  #          
        #   #                                                                        #  #          
        #   #                                                                        #  #          
        #   #                                                                        #  #          
        ####################################           ##################################          
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                               #                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
"""

[layers.background]
image = "bg/bar-town-square.png"

[exits]
right = "7a0deb4d-1adb-499e-a2a9-92229456254a"
